### ISSUE TITLE
getting error file is missing

### ISSUE THREAD

**Issue by prashantnirgun** [mayur091193/quasar-shopping#1]
I am using the following version and getting error

Dev mode.......... spa
 Pkg quasar........ v1.8.5
 Pkg @quasar/app... v1.5.3
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8080)... +5ms
(node:3641) UnhandledPromiseRejectionWarning:   Error: Cannot find module '/home/prashant/www/cloudapmc.com/front.cloudapmc.co  m/.postcssrc.js'
 
(node:3641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3641) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I just downloaded the zip file and extracted then npm install, quasar dev

Ubuntu : 18
quasar : 1.8.5
node : 10.16.0
npm : 6.14.4

Is there anything I am missing ?

**Comment by prashantnirgun** [comment]
I found that file on src folder add it to the git this will  solve the issue. But getting warning can you check out the following warning please

 WARNING  Compiled with 2 warnings                                   12:56:49 PM

 warning  in ./src/pages/home.vue?vue&type=template&id=56b687e3&scoped=true&

Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) <q-carousel-slide v-for="val in [1,2,3]">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

 @ ./src/pages/home.vue?vue&type=template&id=56b687e3&scoped=true& 1:0-285 1:0-285
 @ ./src/pages/home.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

 warning  in ./src/pages/home.vue?vue&type=template&id=56b687e3&scoped=true&

Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) <q-carousel-slide v-for="val in [1,2,3]">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

 @ ./src/pages/home.vue?vue&type=template&id=56b687e3&scoped=true& 1:0-285 1:0-285
 @ ./src/pages/home.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

**Comment by prashantnirgun** [comment]
:key="val" is missing on line no 152 & 72 please fix this and close the ticket.

**Comment by mayur091193** [comment]
Will fix the warning. Thanks for pointing them out.
